[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM4 instead...[0m
[0;33m--- esp-idf-monitor 1.4.0 on \\.\COM4 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x403848b2: rv_utils_wait_for_intr at C:/Espressif/frameworks/esp-idf-v5.2.2/components/riscv/include/riscv/rv_utils.h:52
 (inlined by) esp_cpu_wait_for_intr at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_hw_support/cpu.c:143
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpimd5lyno"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpimd5lyno': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpio7p92s2"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpio7p92s2': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x40048b92: software_reset_cpu in ROM
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmptt4n3u62"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmptt4n3u62': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp07ibavpy"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp07ibavpy': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpp44m_w36"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpp44m_w36': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpq03n_9zz"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpq03n_9zz': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpit59msmc"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpit59msmc': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp1occ_emh"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp1occ_emh': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp9rwffm06"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp9rwffm06': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpilrdqtvc"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpilrdqtvc': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmplboobrin"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmplboobrin': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp2byzp30p"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp2byzp30p': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp3gyrirp4"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmp3gyrirp4': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpcab7a0st"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpcab7a0st': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpj_qk7cb0"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpj_qk7cb0': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0;33m0x42008338: wifi_init_sta at C:/Users/Sayid/workspace/Thesis/Arch-Spin/arch_recive/main/app_main.c:112 (discriminator 1)
[0m
[0;33m0x40385c39: _esp_error_check_failed at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/esp_err.c:50
[0m
[0;33mStack dump detected[0m
[0;33m0x403806d0: panic_abort at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/panic.c:466
0x40385c44: __ubsan_include at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/ubsan.c:313
[0m
[0;33m0x40380001: _vector_table at ??:?
[0m
[0;33mTo exit from IDF monitor please use "Ctrl+]". Alternatively, you can use Ctrl+T Ctrl+X to exit.[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'C:\\Users\\Sayid\\workspace\\Thesis\\Arch-Spin\\arch_recive\\build\\arch_recive.elf', '-ex', 'target remote | "C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe" -m esp_idf_panic_decoder --target esp32c3 "C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpg7mvg0n5"', '-ex', 'bt']' returned non-zero exit status 1.
b"\r\nwarning: could not convert 'main' from the host encoding (CP1252) to UTF-32.\r\nThis normally should not happen, please file a bug report.\r\nerror starting child process 'C:\\Espressif\\python_env\\idf5.2_py3.11_env\\Scripts\\python.exe -m esp_idf_panic_decoder --target esp32c3 C:\\Users\\Sayid\\AppData\\Local\\Temp\\tmpg7mvg0n5': CreateProcess: No such file or directory\r\nNo stack.\r\n"

[0m
[0;33m0x403806bc: esp_restart_noos at C:/Espressif/frameworks/esp-idf-v5.2.2/components/esp_system/port/soc/esp32c3/system_internal.c:111
[0m
[0m
Traceback (most recent call last):
  File "C:\Espressif\frameworks\esp-idf-v5.2.2\tools/idf_monitor.py", line 11, in <module>
    sys.exit(subprocess.run([sys.executable, '-m', 'esp_idf_monitor'] + sys.argv[1:]).returncode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 550, in run
  File "subprocess.py", line 1199, in communicate
  File "subprocess.py", line 1262, in wait
  File "subprocess.py", line 1543, in _wait
KeyboardInterrupt
